Repository ProFile-org/ProFile-BE, pull requests merged in 2023-05, with the labels that each got.

#11 Cuong/configuration
  Dockerfile
  ProFile.sln
  docker-compose.yml
Labels: bug, enhancement

#14 fix: add ports binding and compose as Development environment
  docker-compose.yml
Labels: bug

#15 chore: migrating + seeding
  src/Api/Common/Serilogger.cs
  src/Api/Extensions/HostExtensions.cs
  src/Api/Program.cs
  src/Infrastructure/Infrastructure.csproj
  src/Infrastructure/Persistence/ApplicationDbContextSeed.cs
Labels: enhancement

#17 chore: add full physical domain classes
  src/Domain/Domain.csproj
  src/Domain/Entities/Physical/Borrow.cs
  src/Domain/Entities/Physical/Document.cs
  src/Domain/Entities/Physical/Folder.cs
  src/Domain/Entities/Physical/Locker.cs
  src/Domain/Entities/Physical/Room.cs
  src/Domain/Entities/Physical/Staff.cs
Labels: enhancement

#13 feat: create new user
  src/Api/Controllers/ApiControllerBase.cs
  src/Api/Controllers/UsersController.cs
  src/Application/Application.csproj
  src/Application/Common/Interfaces/IDepartmentRepository.cs
  src/Application/Common/Interfaces/IUnitOfWork.cs
  src/Application/Common/Interfaces/IUserRepository.cs
  src/Application/Common/Models/Dtos/UserDto.cs
  src/Application/Helpers/SecurityUtil.cs
  src/Application/Users/Commands/CreateUserCommand/CreateUserCommand.cs
  src/Infrastructure/ConfigureServices.cs
  src/Infrastructure/Persistence/Configurations/DepartmentConfiguration.cs
  src/Infrastructure/Persistence/Configurations/UserConfiguration.cs
  src/Infrastructure/Repositories/DepartmentRepository.cs
  src/Infrastructure/Repositories/UnitOfWork.cs
  src/Infrastructure/Repositories/UserRepository.cs
Labels: enhancement

#20 feat: create room interface and business logic
  src/Api/Controllers/RoomsController.cs
  src/Application/Application.csproj
  src/Application/Common/Interfaces/IRoomRepository.cs
  src/Application/Common/Interfaces/IStaffRepository.cs
  src/Application/Common/Interfaces/IUnitOfWork.cs
  src/Application/Common/Models/Dtos/RoomDto.cs
  src/Application/Rooms/Commands/CreateRoomCommand.cs
  src/Infrastructure/Repositories/UnitOfWork.cs
  src/Infrastructure/Repositories/UserRepository.cs
Labels: enhancement, help wanted

#23 refactor: fixing and identifying some potential bugs
  src/Api/Controllers/ApiControllerBase.cs
  src/Api/Controllers/UsersController.cs
  src/Api/Extensions/HostExtensions.cs
  src/Api/Extensions/ServiceExtensions.cs
  src/Api/Middlewares/ExceptionMiddleware.cs
  src/Api/appsettings.Development.json
  src/Application/Application.csproj
  src/Application/Common/Interfaces/IUserRepository.cs
  src/Application/ConfigureServices.cs
  src/Application/Users/Commands/CreateUser/CreateUserCommand.cs
  src/Infrastructure/ConfigureServices.cs
  src/Infrastructure/Repositories/UserRepository.cs
Labels: refactoring

#22 feat: implemented the search users by first name
  src/Api/Controllers/UsersController.cs
  src/Application/Application.csproj
  src/Application/Common/Interfaces/IUnitOfWork.cs
  src/Application/Common/Interfaces/Repositories/IDepartmentRepository.cs
  src/Application/Common/Interfaces/Repositories/IUserRepository.cs
  src/Application/Common/Models/Dtos/DepartmentDto.cs
  src/Application/Common/Models/Dtos/UserDto.cs
  src/Application/Users/Queries/GetUserByName/GetUserByNameQuery.cs
  src/Infrastructure/ConfigureServices.cs
  src/Infrastructure/Repositories/DepartmentRepository.cs
  src/Infrastructure/Repositories/UnitOfWork.cs
  src/Infrastructure/Repositories/UserRepository.cs
Labels: enhancement

#24 refactor: fix khoa's life
  src/Api/Controllers/UsersController.cs
  src/Application/Common/Interfaces/IUserRepository.cs
  src/Application/Common/Interfaces/Repositories/IRoomRepository.cs
  src/Application/Common/Interfaces/Repositories/IStaffRepository.cs
  src/Application/Common/Interfaces/Repositories/IUserRepository.cs
  src/Application/Users/Queries/GetUserByName/GetUserByNameQuery.cs
  src/Application/Users/Queries/GetUsersByName/GetUsersByNameQuery.cs
  src/Infrastructure/Repositories/UserRepository.cs
Labels: bug, refactoring

#29 chore: revert migration #3 - snake casing
  src/Infrastructure/Persistence/ApplicationDbContext.cs
  src/Infrastructure/Persistence/Migrations/00000000000003_AddLowerCasingNamingConvention.Designer.cs
  src/Infrastructure/Persistence/Migrations/00000000000003_AddLowerCasingNamingConvention.cs
  src/Infrastructure/Persistence/Migrations/ApplicationDbContextModelSnapshot.cs
Labels: bug

#28 feat: create department
  src/Api/Controllers/DepartmentsController.cs
  src/Application/Common/Interfaces/Repositories/IDepartmentRepository.cs
  src/Application/Departments/Commands/CreateDepartment/CreateDepartmentCommand.cs
  src/Infrastructure/Repositories/DepartmentRepository.cs
Labels: enhancement

#52 Chien/refactor
  ProFile.sln
  src/Api/Controllers/RoomsController.cs
  src/Api/Controllers/StaffsController.cs
  src/Api/Controllers/UsersController.cs
  src/Api/Extensions/ServiceExtensions.cs
  src/Api/IApiMarker.cs
  src/Api/Middlewares/ExceptionMiddleware.cs
  src/Application/Application.csproj
  src/Application/Common/Behaviors/ValidationBehavior.cs
  src/Application/Common/Exceptions/ConflictException.cs
  src/Application/Common/Exceptions/NotAllowedException.cs
  src/Application/Common/Exceptions/RequestValidationException.cs
  src/Application/Common/Interfaces/IApplicationDbContext.cs
  src/Application/Common/Interfaces/IUnitOfWork.cs
  src/Application/Common/Interfaces/Repositories/IDepartmentRepository.cs
  src/Application/Common/Interfaces/Repositories/IRoomRepository.cs
  src/Application/Common/Interfaces/Repositories/IStaffRepository.cs
  src/Application/Common/Interfaces/Repositories/IUserRepository.cs
  src/Application/Common/Models/Dtos/Physical/RoomDto.cs
  src/Application/Common/Models/Dtos/Physical/StaffDto.cs
  src/Application/Common/Models/Dtos/UserDto.cs
  src/Application/ConfigureServices.cs
  src/Application/Departments/Commands/CreateDepartment/CreateDepartmentCommand.cs
  src/Application/Departments/Commands/DeleteDepartment/DeleteDepartmentCommand.cs
  src/Application/Rooms/Commands/CreateRoom/CreateRoomCommand.cs
  src/Application/Rooms/Commands/CreateRoom/CreateRoomCommandValidator.cs
  src/Application/Staffs/Commands/CreateStaff/CreateStaffCommand.cs
  src/Application/Users/Commands/CreateUser/CreateUserCommand.cs
  src/Application/Users/Commands/CreateUser/CreateUserCommandValidator.cs
  src/Application/Users/Commands/DisableUser/DisableUserCommand.cs
  src/Application/Users/Queries/GetUsersByName/GetUsersByNameQuery.cs
  src/Domain/Common/BaseAuditableEntity.cs
  src/Domain/Entities/Physical/Room.cs
  src/Domain/Entities/Physical/Staff.cs
  src/Domain/Entities/User.cs
  src/Domain/Events/UserCreatedEvent.cs
  src/Infrastructure/ConfigureServices.cs
  src/Infrastructure/Infrastructure.csproj
  src/Infrastructure/Persistence/ApplicationDbContext.cs
  src/Infrastructure/Persistence/Configurations/DepartmentConfiguration.cs
  src/Infrastructure/Persistence/Configurations/RoomConfiguration.cs
  src/Infrastructure/Persistence/Configurations/StaffConfiguration.cs
  src/Infrastructure/Persistence/Configurations/UserConfiguration.cs
  src/Infrastructure/Persistence/Migrations/00000000000004_AddStaffAndRoomAndRemoveLowerCaseNamingConvention.Designer.cs
  src/Infrastructure/Persistence/Migrations/00000000000004_AddStaffAndRoomAndRemoveLowerCaseNamingConvention.cs
  src/Infrastructure/Persistence/Migrations/ApplicationDbContextModelSnapshot.cs
  src/Infrastructure/Repositories/DepartmentRepository.cs
  src/Infrastructure/Repositories/UnitOfWork.cs
  src/Infrastructure/Repositories/UserRepository.cs
  tests/Application.Tests.Integration/Application.Tests.Integration.csproj
  tests/Application.Tests.Integration/BaseClassFixture.cs
  tests/Application.Tests.Integration/CustomApiFactory.cs
  tests/Application.Tests.Integration/Departments/Commands/CreateDepartmentTests.cs
  tests/Application.Tests.Integration/Users/Commands/CreateUserTests.cs
  tests/Application.Tests.Unit/Application.Tests.Unit.csproj
  tests/Application.Tests.Unit/Common/Mappings/MappingTests.cs
  tests/Infrastructure.Tests.Unit/Infrastructure.Tests.Unit.csproj
  tests/Infrastructure.Tests.Unit/Repositories/UserRepositoryTests.cs
Labels: bug, enhancement, refactoring

#53 feat: add testablity to dockerfile
  Dockerfile
Labels: enhancement, test

#54 feat: add github action for testing
  .github/workflows/test.yml
Labels: enhancement, test

#55 feat: add workflow to build and push container
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: enhancement

#60 Chien/authentication
  src/Api/ConfigureServices.cs
  src/Api/Controllers/AuthController.cs
  src/Api/Controllers/Payload/LoginModel.cs
  src/Api/Controllers/UsersController.cs
  src/Api/Extensions/WebApplicationExtensions.cs
  src/Api/Program.cs
  src/Api/appsettings.Development.json
  src/Application/Common/Interfaces/IIdentityService.cs
  src/Application/Users/Queries/GetUsersByName/GetUsersByNameQuery.cs
  src/Infrastructure/Authentication/JweAuthenticationHandler.cs
  src/Infrastructure/Authentication/JweAuthenticationOptions.cs
  src/Infrastructure/ConfigureServices.cs
  src/Infrastructure/Infrastructure.csproj
  src/Infrastructure/Shared/JweSettings.cs
Labels: enhancement

#63 Chien/authentication
  src/Api/Controllers/AuthController.cs
  src/Application/Identity/IdentityData.cs
  src/Infrastructure/ConfigureServices.cs
  src/Infrastructure/Identity/Authentication/JweAuthenticationHandler.cs
  src/Infrastructure/Identity/Authentication/JweAuthenticationOptions.cs
  src/Infrastructure/Identity/Authorization/RequiresClaimAttribute.cs
  src/Infrastructure/Infrastructure.csproj
  src/Infrastructure/Persistence/ApplicationDbContext.cs
  src/Infrastructure/Persistence/Migrations/ApplicationDbContextModelSnapshot.cs
Labels: enhancement

#65 add(dbcontext): abstracts dbsets
  src/Application/Common/Interfaces/IApplicationDbContext.cs
Labels: enhancement

#67 fix(dto): add a few more properties to dto
  src/Application/Common/Models/Dtos/Physical/BorrowDto.cs
  src/Application/Common/Models/Dtos/Physical/DocumentDto.cs
Labels: bug, invalid

#64 fix: Long-senpai hit me hard with qemu
  .github/workflows/build.yml
Labels: refactoring

#59 Bao/add locker
  src/Api/Controllers/LockersController.cs
  src/Api/Middlewares/ExceptionMiddleware.cs
  src/Application/Application.csproj
  src/Application/Lockers/Commands/AddLocker/AddLockerCommand.cs
  src/Application/Lockers/Commands/AddLocker/AddLockerCommandValidator.cs
  src/Application/Rooms/Commands/CreateRoom/CreateRoomCommand.cs
  src/Application/Rooms/Commands/CreateRoom/CreateRoomCommandValidator.cs
  src/Domain/Exceptions/LimitExceededException.cs
  src/Infrastructure/Persistence/Configurations/LockerConfiguration.cs
  src/Infrastructure/Persistence/Configurations/RoomConfiguration.cs
Labels: enhancement

#68 Cuong/integration test
  .github/workflows/test.yml
  ProFile.sln
  docker-compose.test.yml
Labels: enhancement, test

#69 Chien/base: Add integration tests baseline
  .github/workflows/test.yml
  docker-compose.test.yml
  tests/Application.Tests.Integration/BaseClassFixture.cs
  tests/Application.Tests.Integration/BaseCollectionFixture.cs
  tests/Application.Tests.Integration/CustomApiFactory.cs
  tests/Application.Tests.Integration/Departments/Commands/CreateDepartmentTests.cs
  tests/Application.Tests.Integration/Users/Commands/CreateUserTests.cs
Labels: enhancement, test

#72 Chien/import document
  src/Api/Controllers/DocumentsController.cs
  src/Api/Controllers/RoomsController.cs
  src/Application/Common/Models/PaginatedList.cs
  src/Application/Documents/Commands/ImportDocument/ImportDocumentCommand.cs
  src/Application/Rooms/Queries/GetEmptyContainersPaginated/EmptyFolderDto.cs
  src/Application/Rooms/Queries/GetEmptyContainersPaginated/EmptyLockerDto.cs
  src/Application/Rooms/Queries/GetEmptyContainersPaginated/GetEmptyContainersPaginatedQuery.cs
  tests/Application.Tests.Integration/BaseClassFixture.cs
  tests/Application.Tests.Integration/Rooms/Queries/GetEmptyContainersPaginatedTests.cs
Labels: enhancement

#75 Bao/disable locker
  src/Api/Controllers/LockersController.cs
  src/Application/Application.csproj
  src/Application/Lockers/Commands/AddLocker/AddLockerCommand.cs
  src/Application/Lockers/Commands/RemoveLocker/RemoveLockerCommand.cs
  tests/Application.Tests.Integration/Application.Tests.Integration.csproj
Labels: enhancement

#80 feat/add-folder
  src/Api/Controllers/FoldersController.cs
  src/Application/Common/Models/PaginatedList.cs
  src/Application/Folders/Commands/AddFolder/AddFolderCommand.cs
  src/Application/Folders/Commands/AddFolder/AddFolderCommandValidator.cs
  tests/Application.Tests.Integration/Folders/Commands/AddFolderTests.cs
Labels: enhancement, test

#74 Bao/add locker tests
  src/Api/Controllers/LockersController.cs
  src/Api/Middlewares/ExceptionMiddleware.cs
  src/Application/Lockers/Commands/AddLocker/AddLockerCommand.cs
  src/Application/Lockers/Commands/DisableLocker/DisableLockerCommand.cs
  src/Application/Lockers/Commands/RemoveLocker/RemoveLockerCommand.cs
  tests/Application.Tests.Integration/Application.Tests.Integration.csproj
  tests/Application.Tests.Integration/Lockers/Commands/AddLockerTests.cs
  tests/Application.Tests.Integration/Lockers/Commands/DisableLockerTests.cs
Labels: enhancement, test

#87 feat: add remove room and its test
  src/Api/Controllers/RoomsController.cs
  src/Api/Middlewares/ExceptionMiddleware.cs
  src/Application/Rooms/Commands/RemoveRoom/RemoveRoomCommand.cs
  src/Application/Rooms/Commands/RemoveRoom/RemoveRoomCommandValidator.cs
  tests/Application.Tests.Integration/BaseClassFixture.cs
  tests/Application.Tests.Integration/Rooms/Commands/RemoveRoomTests.cs
Labels: enhancement

#88 Feat/disable-folder
  src/Api/Controllers/FoldersController.cs
  src/Api/Middlewares/ExceptionMiddleware.cs
  src/Application/Folders/Commands/AddFolder/AddFolderCommandValidator.cs
  src/Application/Folders/Commands/DisableFolder/DisableFolderCommand.cs
  src/Application/Folders/Commands/DisableFolder/DisableFolderCommandValidator.cs
  tests/Application.Tests.Integration/Folders/Commands/AddFolderTests.cs
  tests/Application.Tests.Integration/Folders/Commands/DisableFolderTests.cs
Labels: enhancement

#99 feat: add volume to docker compose file
  docker-compose.yml
Labels: enhancement

#105 Cuong/refactor
  src/Api/Controllers/AuthController.cs
  src/Api/Controllers/DepartmentsController.cs
  src/Api/Controllers/DocumentsController.cs
  src/Api/Controllers/FoldersController.cs
  src/Api/Controllers/LockersController.cs
  src/Api/Controllers/RoomsController.cs
  src/Api/Controllers/StaffsController.cs
  src/Api/Controllers/UsersController.cs
  src/Api/Middlewares/ExceptionMiddleware.cs
  src/Application/Departments/Commands/AddDepartment/AddDepartmentCommand.cs
  src/Application/Documents/Commands/ImportDocument/ImportDocumentCommand.cs
  src/Application/Folders/Commands/AddFolder/AddFolderCommand.cs
  src/Application/Folders/Commands/DisableFolder/DisableFolderCommand.cs
  src/Application/Lockers/Commands/AddLocker/AddLockerCommand.cs
  src/Application/Rooms/Commands/AddRoom/AddRoomCommand.cs
  src/Application/Rooms/Commands/AddRoom/AddRoomCommandValidator.cs
  src/Application/Rooms/Commands/CreateRoom/CreateRoomCommand.cs
  src/Application/Rooms/Commands/DisableRoom/DisableRoomCommand.cs
  src/Application/Rooms/Queries/GetEmptyContainersPaginated/GetEmptyContainersPaginatedQuery.cs
  src/Application/Staffs/Commands/AddStaff/AddStaffCommand.cs
  src/Application/Users/Commands/AddUser/AddUserCommand.cs
  src/Application/Users/Commands/AddUser/AddUserCommandValidator.cs
  src/Application/Users/Commands/DisableUser/DisableUserCommand.cs
  tests/Application.Tests.Integration/BaseClassFixture.cs
  tests/Application.Tests.Integration/CustomApiFactory.cs
  tests/Application.Tests.Integration/Departments/Commands/AddDepartmentTests.cs
  tests/Application.Tests.Integration/Folders/Commands/AddFolderTests.cs
  tests/Application.Tests.Integration/Folders/Commands/DisableFolderTests.cs
  tests/Application.Tests.Integration/Lockers/Commands/AddLockerTests.cs
  tests/Application.Tests.Integration/Rooms/Commands/DisableRoomTests.cs
  tests/Application.Tests.Integration/Users/Commands/AddUserTests.cs
Labels: refactoring

#107 Update/auth mechanism
  src/Api/Controllers/AuthController.cs
  src/Infrastructure/Identity/IdentityService.cs
Labels: enhancement

#108 Add/queries commands
  src/Api/Controllers/AuthController.cs
  src/Api/Controllers/DepartmentsController.cs
  src/Api/Controllers/DocumentsController.cs
  src/Api/Controllers/FoldersController.cs
  src/Api/Controllers/LockersController.cs
  src/Api/Controllers/Payload/Requests/Documents/UpdateDocumentRequest.cs
  src/Api/Controllers/Payload/Requests/Folders/GetAllFoldersPaginatedQueryParameters.cs
  src/Api/Controllers/Payload/Requests/Folders/UpdateFolderRequest.cs
  src/Api/Controllers/Payload/Requests/Lockers/GetAllLockersPaginatedQueryParameters.cs
  src/Api/Controllers/Payload/Requests/Lockers/UpdateLockerRequest.cs
  src/Api/Controllers/Payload/Requests/Staffs/GetAllStaffsPaginatedQueryParameters.cs
  src/Api/Controllers/Payload/Requests/Staffs/RemoveStaffFromRoomRequest.cs
  src/Api/Controllers/Payload/Requests/UpdateDepartmentRequest.cs
  src/Api/Controllers/Payload/Requests/UpdateRoomRequest.cs
  src/Api/Controllers/Payload/Requests/Users/GetAllUsersPaginatedQueryParameters.cs
  src/Api/Controllers/Payload/Requests/Users/UpdateUserRequest.cs
  src/Api/Controllers/RoomsController.cs
  src/Api/Controllers/StaffsController.cs
  src/Api/Controllers/UsersController.cs
  src/Application/Departments/Commands/UpdateDepartment/UpdateDepartmentCommand.cs
  src/Application/Departments/Queries/GetDepartmentById/GetDepartmentByIdQuery.cs
  src/Application/Documents/Commands/DeleteDocument/DeleteDocumentCommand.cs
  src/Application/Documents/Commands/UpdateDocument/UpdateDocumentCommand.cs
  src/Application/Folders/Commands/EnableFolder/EnableFolderCommand.cs
  src/Application/Folders/Commands/RemoveFolder/RemoveFolderCommand.cs
  src/Application/Folders/Commands/UpdateFolder/UpdateFolderCommand.cs
  src/Application/Folders/Queries/GetAllFoldersPaginated/GetAllFoldersPaginatedQuery.cs
  src/Application/Folders/Queries/GetFolderById/GetFolderByIdQuery.cs
  src/Application/Lockers/Commands/RemoveLocker/RemoveLockerCommand.cs
  src/Application/Lockers/Commands/UpdateLocker/UpdateLockerCommand.cs
  src/Application/Lockers/Queries/GetAllLockersPaginated/GetAllLockersPaginatedQuery.cs
  src/Application/Lockers/Queries/GetLockerById/GetLockerByIdQuery.cs
  src/Application/Rooms/Commands/EnableRoom/EnableRoomCommand.cs
  src/Application/Rooms/Commands/UpdateRoom/UpdateRoomCommand.cs
  src/Application/Rooms/Queries/GetAllRoomPaginated/GetAllRoomsPaginatedQuery.cs
  src/Application/Rooms/Queries/GetRoomById/GetRoomByIdQuery.cs
  src/Application/Staffs/Commands/RemoveStaffFromRoom/RemoveStaffFromRoomCommand.cs
  src/Application/Staffs/Queries/GetAllStaffsPaginated/GetAllStaffsPaginatedQuery.cs
  src/Application/Staffs/Queries/GetStaffById/GetStaffByIdQuery.cs
  src/Application/Staffs/Queries/GetStaffByRoom/GetStaffByRoomQuery.cs
  src/Application/Users/Commands/EnableUser/EnableUserCommand.cs
  src/Application/Users/Commands/UpdateUser/UpdateUserCommand.cs
  src/Application/Users/Queries/GetAllUsersPaginated/GetAllUsersPaginatedQuery.cs
  src/Application/Users/Queries/GetUserById/GetUserByIdQuery.cs
Labels: enhancement

#110 feat: Create codeql.yml
  .github/workflows/codeql.yml
Labels: enhancement

#114 Feat/get room by ID
  src/Application/Rooms/Queries/GetRoomById.cs
  tests/Application.Tests.Integration/Rooms/Queries/GetRoomByIdTests.cs
Labels: enhancement

#112 Feat/enable room
  src/Application/Common/Models/Dtos/Physical/RoomDto.cs
  src/Application/Rooms/Commands/EnableRoom.cs
  tests/Application.Tests.Integration/Rooms/Commands/EnableRoomTests.cs
Labels: enhancement

#135 Feat/remove locker
  src/Application/Common/Models/Dtos/DepartmentDto.cs
  src/Application/Common/Models/Dtos/Physical/RoomDto.cs
  src/Application/Lockers/Commands/DisableLocker.cs
  src/Application/Lockers/Commands/RemoveLocker.cs
  src/Application/Rooms/Commands/AddRoom.cs
  src/Application/Rooms/Commands/DisableRoom.cs
  src/Application/Rooms/Commands/RemoveRoom.cs
  tests/Application.Tests.Integration/Lockers/Commands/RemoveLockerTests.cs
Labels: enhancement

#136 Feat/update locker
  src/Application/Departments/Queries/GetAllDepartments.cs
  src/Application/Lockers/Commands/UpdateLocker.cs
  tests/Application.Tests.Integration/Lockers/Commands/UpdateLockerTests.cs
Labels: enhancement
