Repository ProFile-org/ProFile-BE, pull requests merged in 2023-07, with the labels that each got.

#317 entrydto to file id
  src/Application/Common/Models/Dtos/Physical/DocumentDto.cs
Labels: bug

#318 fix: fix condition for checking base directory
  src/Application/Digital/Commands/UploadDigitalFile.cs
Labels: bug

#298 refactor: runable test
  tests/Application.Tests.Integration/Application.Tests.Integration.csproj
  tests/Application.Tests.Integration/Borrows/Commands/ApproveBorrowRequestTests.cs
  tests/Application.Tests.Integration/Borrows/Commands/BorrowDocumentTests.cs
  tests/Application.Tests.Integration/Borrows/Commands/UpdateBorrowTests.cs
  tests/Application.Tests.Integration/Departments/Queries/GetDepartmentByIdTests.cs
  tests/Application.Tests.Integration/Documents/Commands/DeleteDocumentTests.cs
  tests/Application.Tests.Integration/Documents/Commands/UpdateDocumentTests.cs
  tests/Application.Tests.Integration/Documents/Queries/GetAllDocumentsPaginatedTests.cs
  tests/Application.Tests.Integration/Folders/Commands/AddFolderTests.cs
  tests/Application.Tests.Integration/Folders/Commands/RemoveFolderTests.cs
  tests/Application.Tests.Integration/Folders/Commands/UpdateFolderTests.cs
  tests/Application.Tests.Integration/Folders/Queries/GetAllFoldersPaginatedTests.cs
  tests/Application.Tests.Integration/Folders/Queries/GetFolderByIdTests.cs
  tests/Application.Tests.Integration/Lockers/Commands/AddLockerTests.cs
  tests/Application.Tests.Integration/Lockers/Commands/RemoveLockerTests.cs
  tests/Application.Tests.Integration/Lockers/Commands/UpdateLockerTests.cs
  tests/Application.Tests.Integration/Lockers/Queries/GetAllLockersPaginatedTests.cs
  tests/Application.Tests.Integration/Lockers/Queries/GetLockerByIdTests.cs
  tests/Application.Tests.Integration/Rooms/Commands/RemoveRoomTests.cs
  tests/Application.Tests.Integration/Rooms/Commands/UpdateRoomTests.cs
  tests/Application.Tests.Integration/Rooms/Queries/GetAllRoomsPaginatedTests.cs
  tests/Application.Tests.Integration/Rooms/Queries/GetRoomByIdTests.cs
  tests/Application.Tests.Integration/Staffs/Commands/RemoveStaffFromRoomTests.cs
  tests/Application.Tests.Integration/Staffs/Queries/GetAllStaffsPaginatedTests.cs
  tests/Application.Tests.Integration/Staffs/Queries/GetStaffByRoomTests.cs
  tests/Application.Tests.Integration/Users/Commands/AddUserTests.cs
  tests/Application.Tests.Integration/Users/Commands/UpdateUserTests.cs
  tests/Application.Tests.Integration/Users/Queries/GetUserByIdTests.cs
Labels: test

#336 feat: share permission for entries
  src/Api/Controllers/EntriesController.cs
  src/Api/Controllers/Payload/Requests/DigitalFile/ShareEntryPermissionRequest.cs
  src/Application/Common/Models/Dtos/Digital/EntryPermissionDto.cs
  src/Application/Digital/Commands/ShareEntry.cs
Labels: enhancement

#340 Feat/get shared entries
  src/Api/Controllers/Payload/Requests/Entries/GetAllEntriesPaginatedQueryParameters.cs
  src/Api/Controllers/SharedController.cs
  src/Application/Entries/Queries/GetAllSharedEntriesPaginated.cs
Labels: enhancement

#221 feat/handle lost report
  src/Api/Controllers/BorrowsController.cs
  src/Application/Borrows/Commands/ReportLostDocument.cs
  tests/Application.Tests.Integration/Borrows/Commands/BorrowDocumentTests.cs
Labels: enhancement, test

#327 feat: get entry by id
  src/Api/Controllers/EntriesController.cs
  src/Application/Digital/Queries/GetEntryById.cs
Labels: enhancement

#341 feat: get shared entry permission
  src/Api/Controllers/SharedController.cs
  src/Application/Entries/Queries/GetPermissions.cs
Labels: enhancement

#331 feat: get entries by entry path paginated
  src/Api/Controllers/EntriesController.cs
  src/Api/Controllers/Payload/Requests/DigitalFile/GetAllEntriesPaginatedQueryParameters.cs
  src/Application/Digital/Queries/GetAllEntriesPaginated.cs
Labels: enhancement

#347 implement getting shared users
  src/Api/Controllers/Payload/Requests/Users/GetAllSharedUsersOfASharedEntryPaginatedQueryParameters.cs
  src/Api/Controllers/SharedController.cs
  src/Application/Users/Queries/GetAllSharedUsersOfASharedEntryPaginated.cs
Labels: enhancement

#277 fix: made description not required when adding a room.
  src/Application/Rooms/Commands/AddRoom.cs
Labels: bug

#345 Feat/download shared files
  src/Api/Controllers/SharedController.cs
  src/Application/Entries/Queries/DownloadSharedEntry.cs
Labels: enhancement

#325 feat: implement deleting entry in bin
  src/Api/Controllers/BinController.cs
  src/Api/Middlewares/ExceptionMiddleware.cs
  src/Application/Common/Exceptions/NotChangedException.cs
  src/Application/Digital/Commands/DeleteBinEntry.cs
Labels: enhancement

#278 update: added role checking when adding user
  src/Application/Users/Commands/AddUser.cs
Labels: enhancement

#343 Feat : Upload file or create directory on shared entry by entry ID
  src/Api/Controllers/Payload/Requests/DigitalFile/UploadSharedEntryRequest.cs
  src/Api/Controllers/SharedController.cs
  src/Application/Digital/Commands/UploadSharedEntry.cs
Labels: enhancement

#284 fix: a couple things
  src/Api/Controllers/ImportRequestsController.cs
  src/Api/Controllers/Payload/Requests/ImportRequests/GetAllImportRequestsPaginatedQueryParameters.cs
  src/Application/ImportRequests/Queries/GetAllImportRequestsPaginated.cs
Labels: bug, enhancement

#286 fix: get rooms by department id
  src/Api/Controllers/DepartmentsController.cs
  src/Application/Common/Models/ItemResult.cs
  src/Application/Rooms/Queries/GetRoomByDepartmentId.cs
Labels: bug

#329 feat: download digital file
  src/Api/Controllers/EntriesController.cs
  src/Application/Digital/Commands/DownloadDigitalFile.cs
Labels: enhancement

#332 feat: update entry
  src/Api/Controllers/EntriesController.cs
  src/Api/Controllers/Payload/Requests/Entries/UpdateEntryRequest.cs
  src/Application/Digital/Commands/UpdateEntry.cs
Labels: enhancement

#287 update: a couple things
  src/Api/Controllers/BorrowsController.cs
  src/Api/Controllers/Payload/Requests/Borrows/GetAllBorrowRequestsPaginatedQueryParameters.cs
  src/Application/Borrows/Queries/GetAllBorrowRequestsPaginated.cs
Labels: enhancement

#349 implement getting shared entry by id
  src/Api/Controllers/SharedController.cs
  src/Application/Entries/Queries/GetSharedEntryById.cs
Labels: enhancement

#322 feat: implement restoring entry
  src/Api/Controllers/BinController.cs
  src/Api/Middlewares/ExceptionMiddleware.cs
  src/Application/Digital/Commands/RestoreBinEntry.cs
Labels: enhancement

#354 hotfix: bug in role auth
  src/Api/Controllers/DocumentsController.cs
Labels: bug

#355 refactor: wrap get all departments with items
  src/Api/Controllers/DepartmentsController.cs
  src/Application/Departments/Queries/GetAllDepartments.cs
  tests/Application.Tests.Integration/Departments/Queries/GetAllDepartmentsTests.cs
Labels: bug

#352 hotfix: mismapping import request entity with dto
  src/Application/ImportRequests/Commands/AssignDocument.cs
Labels: bug

#320 feat: implement moving entry to trash bin
  src/Api/Controllers/BinController.cs
  src/Application/Digital/Commands/MoveEntryToBin.cs
Labels: enhancement

#356 fix: filter issued status for get all documents for employee and get …
  src/Application/Documents/Queries/GetAllDocumentsForEmployeePaginated.cs
  src/Application/Documents/Queries/GetDocumentById.cs
Labels: bug

#357 hotfix: improper import request status in checkin
  src/Application/ImportRequests/Commands/CheckinDocument.cs
Labels: bug

#361 update: users first times login with default password now are returne…
  src/Api/Controllers/AuthController.cs
  src/Api/Controllers/Payload/Responses/NotActivatedLoginResut.cs
  src/Application/Application.csproj
  src/Application/Common/Interfaces/IIdentityService.cs
  src/Infrastructure/Identity/IdentityService.cs
  src/Infrastructure/Infrastructure.csproj
Labels: enhancement

#311 update: merge background services into one class
  src/Api/ConfigureServices.cs
  src/Api/Services/BackgroundWorkers.cs
  src/Api/Services/ExpiryPermissionService.cs
Labels: enhancement

#362 feat: add logs to entries
  src/Application/Common/Messages/EntryLogMessages.cs
  src/Application/Entries/Commands/DeleteBinEntry.cs
  src/Application/Entries/Commands/DownloadDigitalFile.cs
  src/Application/Entries/Commands/MoveEntryToBin.cs
  src/Application/Entries/Commands/RestoreBinEntry.cs
  src/Application/Entries/Commands/ShareEntry.cs
  src/Application/Entries/Commands/UpdateEntry.cs
  src/Application/Entries/Commands/UploadDigitalFile.cs
  src/Application/Entries/Commands/UploadSharedEntry.cs
  src/Application/Entries/EntryLogExtension.cs
Labels: enhancement

#367 fix: delete shared download file
  src/Api/Controllers/SharedController.cs
  src/Application/Entries/Commands/DownloadDigitalFile.cs
  src/Application/Entries/Queries/DownloadSharedEntry.cs
Labels: bug

#368 fix: NotAllowedException to UnauthorizedAccessException
  src/Application/Entries/Commands/DeleteBinEntry.cs
  src/Application/Entries/Commands/MoveEntryToBin.cs
  src/Application/Entries/Commands/RestoreBinEntry.cs
Labels: bug

#366 fix: regex validation and change command name.
  src/Api/Controllers/EntriesController.cs
  src/Api/Controllers/SharedController.cs
  src/Application/Entries/Commands/CreateEntry.cs
  src/Application/Entries/Commands/CreateSharedEntry.cs
  src/Application/Entries/Commands/UpdateEntry.cs
  src/Application/Entries/EntryLogExtension.cs
  src/Application/Entries/Queries/GetAllEntriesPaginated.cs
Labels: bug

#372 fix regex
  src/Application/Entries/Commands/CreateEntry.cs
  src/Application/Entries/Queries/GetAllEntriesPaginated.cs
Labels: bug

#369 feat/get bin entries and get bin entry by id
  src/Api/Controllers/BinController.cs
  src/Api/Controllers/EntriesController.cs
  src/Api/Controllers/Payload/Requests/BinEntries/GetAllBinEntriesPaginatedQueryParameters.cs
  src/Application/Entries/Queries/GetAllBinEntriesPaginated.cs
  src/Application/Entries/Queries/GetBinEntryById.cs
Labels: enhancement

#375 fix
  src/Application/Users/Queries/GetAllSharedUsersOfASharedEntryPaginated.cs
Labels: bug

#373 fix: log entries
  src/Api/Api.csproj
  src/Api/Controllers/EntriesController.cs
  src/Application/Common/Messages/EntryLogMessages.cs
  src/Application/Entries/Commands/CreateEntry.cs
  src/Application/Entries/Commands/CreateSharedEntry.cs
  src/Application/Entries/Commands/DeleteBinEntry.cs
  src/Application/Entries/Commands/DownloadDigitalFile.cs
  src/Application/Entries/Commands/MoveEntryToBin.cs
  src/Application/Entries/Commands/RestoreBinEntry.cs
  src/Application/Entries/Commands/ShareEntry.cs
  src/Application/Entries/Commands/UpdateEntry.cs
  src/Application/Entries/EntryLogExtension.cs
Labels: bug

#365 refactor: add entries api documentation
  src/Api/Controllers/BinController.cs
  src/Api/Controllers/EntriesController.cs
  src/Api/Controllers/SharedController.cs
Labels: documentation

#379 refactor restore logic
  src/Application/Entries/Commands/RestoreBinEntry.cs
Labels: bug

#380 fix: admin can see borrow request by id
  src/Api/Controllers/BorrowsController.cs
  src/Application/Borrows/Queries/GetBorrowRequestById.cs
Labels: bug

#382 Finale/khoa last touch
  src/Api/Controllers/BorrowsController.cs
  src/Application/Entries/Commands/CreateEntry.cs
  src/Application/Entries/Commands/CreateSharedEntry.cs
  src/Application/Entries/Commands/DownloadDigitalFile.cs
  src/Application/Entries/Queries/GetAllEntriesPaginated.cs
  src/Application/Loggings/Queries/GetAllRequestLogsPaginated.cs
Labels: bug

#385 add: overdue worker service
  src/Api/Services/BackgroundWorkers.cs
  src/Application/Loggings/Queries/GetAllLogsPaginated.cs
Labels: enhancement

#383 Fix/entry
  src/Application/Entries/Commands/CreateEntry.cs
  src/Application/Entries/Commands/MoveEntryToBin.cs
  src/Application/Entries/Commands/RestoreBinEntry.cs
  src/Application/Entries/Commands/UpdateEntry.cs
Labels: bug

#391 feat: get all shared users for a document
  src/Api/Controllers/DocumentsController.cs
  src/Api/Controllers/Payload/Requests/Users/GetAllSharedUsersOfASharedEntryPaginatedQueryParameters.cs
  src/Api/Controllers/SharedController.cs
  src/Application/Common/Models/Dtos/Physical/PermissionDto.cs
  src/Application/Documents/Queries/GetAllSharedUsersOfDocumentPaginated.cs
Labels: enhancement

#389 feat: found a lost document
  src/Api/Controllers/BorrowsController.cs
  src/Application/Borrows/Commands/ReportFoundDocument.cs
Labels: enhancement, help wanted

#396 fix: include issuer
  src/Application/ImportRequests/Queries/GetImportRequestById.cs
Labels: bug
