Repository ProFile-org/ProFile-BE, pull requests merged in 2023-06, with the labels that each got.

#139 fix/get all folders paginated
  src/Application/Folders/Queries/GetAllFoldersPaginated.cs
Labels: bug

#140 Feat/get folder by Id
  src/Application/Folders/Queries/GetFolderById.cs
  tests/Application.Tests.Integration/Folders/Queries/GetFolderByIdTests.cs
Labels: enhancement

#115 Feat/update room
  src/Application/Rooms/Commands/UpdateRoom.cs
  tests/Application.Tests.Integration/Rooms/Commands/UpdateRoomTests.cs
Labels: enhancement, help wanted

#142 Feat/remove staff
  src/Api/Controllers/StaffsController.cs
  src/Application/Staffs/Commands/RemoveStaff.cs
  tests/Application.Tests.Integration/Staffs/Commands/RemoveStaffTests.cs
Labels: enhancement, test

#154 Feat/get department by id
  src/Application/Departments/Queries/GetDepartmentById.cs
  tests/Application.Tests.Integration/Departments/Queries/GetDepartmentByIdTests.cs
Labels: enhancement

#155 Feat/get locker by id
  src/Application/Lockers/Queries/GetLockerById.cs
  tests/Application.Tests.Integration/Lockers/Queries/GetLockerByIdTests.cs
Labels: enhancement

#141 Feat/remove folder
  src/Application/Folders/Commands/RemoveFolder.cs
  tests/Application.Tests.Integration/Folders/Commands/RemoveFolderTests.cs
Labels: enhancement

#144 Feat/enable folder
  src/Application/Folders/Commands/EnableFolder.cs
  tests/Application.Tests.Integration/Folders/Commands/EnableFolderTests.cs
Labels: enhancement

#156 feat: remove user from room + tests
  src/Api/Controllers/StaffsController.cs
  src/Application/Staffs/Commands/RemoveStaffFromRoom.cs
  tests/Application.Tests.Integration/Staffs/Commands/RemoveStaffFromRoomTests.cs
Labels: enhancement, test

#145 Feat/reset password email
  src/Api/Controllers/Payload/Requests/Users/AddUserRequest.cs
  src/Api/Controllers/UsersController.cs
  src/Api/Program.cs
  src/Api/appsettings.Development.json
  src/Application/Application.csproj
  src/Application/Common/Interfaces/IMailService.cs
  src/Application/Common/Models/HTMLMailData.cs
  src/Application/Helpers/StringUtil.cs
  src/Application/Users/Commands/AddUser.cs
  src/Application/Users/EventHandlers/UserCreatedEventHandler.cs
  src/Domain/Events/UserCreatedEvent.cs
  src/Infrastructure/ConfigureServices.cs
  src/Infrastructure/Infrastructure.csproj
  src/Infrastructure/Services/MailService.cs
  src/Infrastructure/Shared/MailSettings.cs
  tests/Application.Tests.Integration/CustomApiFactory.cs
  tests/Application.Tests.Integration/CustomMailService.cs
  tests/Application.Tests.Integration/Users/Commands/AddUserTests.cs
Labels: enhancement

#151 feat: get staff by room + tests
  src/Application/Staffs/Queries/GetStaffByRoom.cs
  tests/Application.Tests.Integration/Staffs/Queries/GetStaffByRoomTests.cs
Labels: enhancement, test

#138 add: integration test and implementation
  src/Api/Controllers/UsersController.cs
  src/Application/Users/Queries/GetAllUsersPaginated.cs
  tests/Application.Tests.Integration/Users/Queries/GetAllUsersPaginatedTests.cs
Labels: enhancement, test

#137 Feat/get all documents
  src/Application/Documents/Queries/GetAllDocumentsPaginated.cs
  tests/Application.Tests.Integration/Documents/Queries/GetAllDocumentsPaginatedTests.cs
Labels: enhancement, test

#168 fix: import document
  src/Application/Documents/Commands/ImportDocument.cs
Labels: bug

#163 Feat/delete document
  src/Application/Documents/Commands/DeleteDocument.cs
  tests/Application.Tests.Integration/Documents/Commands/DeleteDocumentTests.cs
Labels: enhancement

#173 feat: get staff by id
  src/Application/Staffs/Queries/GetStaffById.cs
  tests/Application.Tests.Integration/Staffs/Queries/GetStaffByIdTests.cs
Labels: enhancement

#159 Feat/borrow
  docker-compose.test.yml
  src/Api/ConfigureServices.cs
  src/Api/Controllers/BorrowsController.cs
  src/Api/Controllers/DocumentsController.cs
  src/Api/Controllers/Payload/Requests/Borrows/BorrowDocumentRequest.cs
  src/Api/Controllers/Payload/Requests/Borrows/GetAllBorrowRequestsPaginatedAsAdminQueryParameters.cs
  src/Api/Controllers/Payload/Requests/Borrows/GetAllBorrowRequestsPaginatedAsEmployeeQueryParameters.cs
  src/Api/Controllers/Payload/Requests/Borrows/GetAllBorrowRequestsPaginatedAsStaffQueryParameters.cs
  src/Api/Controllers/Payload/Requests/Borrows/GetAllBorrowRequestsPaginatedForDocumentQueryParameters.cs
  src/Api/Controllers/Payload/Requests/Borrows/UpdateBorrowRequest.cs
  src/Api/Controllers/Payload/Requests/Documents/GetAllDocumentsPaginatedQueryParameters.cs
  src/Api/Controllers/Payload/Requests/Folders/GetAllFoldersPaginatedQueryParameters.cs
  src/Api/Controllers/Payload/Requests/Lockers/GetAllLockersPaginatedQueryParameters.cs
  src/Api/Controllers/Payload/Requests/PaginatedQueryParameters.cs
  src/Api/Controllers/Payload/Requests/Rooms/GetAllRoomsPaginatedQueryParameters.cs
  src/Api/Controllers/Payload/Requests/Staffs/GetAllStaffsPaginatedQueryParameters.cs
  src/Api/Controllers/Payload/Requests/Users/GetAllUsersPaginatedQueryParameters.cs
  src/Api/Controllers/RoomsController.cs
  src/Api/Program.cs
  src/Api/Services/CurrentUserService.cs
  src/Application/Borrows/Commands/ApproveBorrowRequest.cs
  src/Application/Borrows/Commands/BorrowDocument.cs
  src/Application/Borrows/Commands/CancelBorrowRequest.cs
  src/Application/Borrows/Commands/CheckoutDocument.cs
  src/Application/Borrows/Commands/RejectBorrowRequest.cs
  src/Application/Borrows/Commands/ReturnDocument.cs
  src/Application/Borrows/Commands/UpdateBorrow.cs
  src/Application/Borrows/Queries/GetAllBorrowRequestsPaginated.cs
  src/Application/Borrows/Queries/GetAllBorrowRequestsSpecificPaginated.cs
  src/Application/Common/Extensions/QueryableExtensions.cs
  src/Application/Common/Interfaces/ICurrentUserService.cs
  src/Application/Common/Models/Dtos/Physical/BorrowDto.cs
  src/Application/Common/Models/Dtos/Physical/DocumentDto.cs
  src/Application/Documents/Commands/ImportDocument.cs
  src/Application/Documents/Queries/GetAllDocumentsPaginated.cs
  src/Application/Folders/Queries/GetAllFoldersPaginated.cs
  src/Application/Lockers/Queries/GetAllLockersPaginated.cs
  src/Application/Rooms/Queries/GetAllRoomsPaginated.cs
  src/Application/Staffs/Commands/AddStaff.cs
  src/Domain/Entities/Physical/Borrow.cs
  src/Domain/Entities/Physical/Document.cs
  src/Domain/Statuses/BorrowRequestStatus.cs
  src/Domain/Statuses/DocumentStatus.cs
  src/Infrastructure/Identity/IdentityService.cs
  src/Infrastructure/Persistence/Configurations/BorrowConfiguration.cs
  src/Infrastructure/Persistence/Configurations/DocumentConfiguration.cs
  src/Infrastructure/Persistence/Migrations/00000000000009_RoomMustHaveADepartment.cs
  src/Infrastructure/Persistence/Migrations/00000000000010_UpdateBorrow.Designer.cs
  src/Infrastructure/Persistence/Migrations/00000000000010_UpdateBorrow.cs
  src/Infrastructure/Persistence/Migrations/ApplicationDbContextModelSnapshot.cs
  src/Infrastructure/Services/MailService.cs
  tests/Application.Tests.Integration/Folders/Commands/DisableFolderTests.cs
  tests/Application.Tests.Integration/Lockers/Commands/AddLockerTests.cs
Labels: enhancement, test

#165 Feat/get all staffs paginated + tests
  src/Application/Common/Models/Dtos/Physical/StaffDto.cs
  src/Application/Staffs/Queries/GetAllStaffsPaginated.cs
  tests/Application.Tests.Integration/Staffs/Queries/GetAllStaffsPaginatedTests.cs
Labels: enhancement, test

#169 Feat/update document
  src/Application/Documents/Commands/UpdateDocument.cs
  tests/Application.Tests.Integration/Documents/Commands/UpdateDocumentTests.cs
Labels: enhancement

#175 fix: added room checking for updating locker
  src/Application/Lockers/Commands/UpdateLocker.cs
  tests/Application.Tests.Integration/Lockers/Commands/UpdateLockerTests.cs
Labels: bug, enhancement

#178 Fix/logic error in update
  src/Application/Folders/Commands/UpdateFolder.cs
Labels: bug

#179 idek what to write here
  src/Api/Controllers/BorrowsController.cs
  src/Api/Services/CurrentUserService.cs
  src/Application/Borrows/Queries/GetBorrowRequestById.cs
Labels: enhancement

#182 now can request a borrow even when a previous request of a user is ca…
  src/Api/Controllers/BorrowsController.cs
  src/Api/Controllers/Payload/Requests/Borrows/GetAllBorrowRequestsPaginatedForDocumentQueryParameters.cs
  src/Application/Borrows/Commands/BorrowDocument.cs
  src/Application/Borrows/Queries/GetAllBorrowRequestsPaginated.cs
Labels: bug

#180 Refactor/include fix
  src/Application/Folders/Commands/DisableFolder.cs
  src/Application/Folders/Commands/EnableFolder.cs
  src/Application/Folders/Commands/RemoveFolder.cs
  src/Application/Folders/Commands/UpdateFolder.cs
  src/Application/Folders/Queries/GetFolderById.cs
  src/Application/Lockers/Commands/DisableLocker.cs
  src/Application/Lockers/Commands/EnableLocker.cs
  src/Application/Lockers/Commands/RemoveLocker.cs
  src/Application/Lockers/Commands/UpdateLocker.cs
  src/Application/Lockers/Queries/GetLockerById.cs
  src/Application/Rooms/Commands/DisableRoom.cs
  src/Application/Rooms/Commands/EnableRoom.cs
  src/Application/Rooms/Commands/RemoveRoom.cs
  src/Application/Rooms/Commands/UpdateRoom.cs
  src/Application/Rooms/Queries/GetAllRoomsPaginated.cs
  src/Application/Rooms/Queries/GetRoomById.cs
  src/Application/Users/Queries/GetUserById.cs
Labels: refactoring

#184 fix: pagination working wrong
  src/Application/Borrows/Queries/GetAllBorrowRequestsPaginated.cs
  src/Application/Documents/Queries/GetAllDocumentsPaginated.cs
  src/Application/Folders/Queries/GetAllFoldersPaginated.cs
  src/Application/Lockers/Queries/GetAllLockersPaginated.cs
  src/Application/Rooms/Queries/GetAllRoomsPaginated.cs
  src/Application/Staffs/Queries/GetAllStaffsPaginated.cs
  src/Application/Users/Queries/GetAllUsersPaginated.cs
Labels: bug

#192 test: create borrow request in test
  tests/Application.Tests.Integration/BaseClassFixture.cs
Labels: test

#209 test: add integration tests for update borrow request
  tests/Application.Tests.Integration/BaseClassFixture.cs
  tests/Application.Tests.Integration/Borrows/Commands/UpdateBorrowTests.cs
Labels: test

#236 feat: modified get all documents
  src/Application/Documents/Queries/GetAllDocumentsPaginated.cs
Labels: refactoring

#247 feat: get user log by id + get user logs paginated
  src/Api/Controllers/Payload/Requests/GetAllLogsPaginatedQueryParameters.cs
  src/Api/Controllers/UsersController.cs
  src/Application/Common/Models/Dtos/Logging/UserLogDto.cs
  src/Application/Users/Queries/GetAllUserLogsPaginated.cs
  src/Application/Users/Queries/GetUserLogById.cs
Labels: enhancement

#251 feat: get folder log by id + get folder logs paginated
  src/Api/Controllers/FoldersController.cs
  src/Application/Common/Models/Dtos/Logging/FolderLogDto.cs
  src/Application/Folders/Queries/GetAllFolderLogsPaginated.cs
  src/Application/Folders/Queries/GetFolderLogById.cs
Labels: enhancement

#256 Feat: implement get locker logs paginated + get locker log by id
  src/Api/Controllers/LockersController.cs
  src/Application/Common/Models/Dtos/Logging/LockerLogDto.cs
  src/Application/Lockers/Queries/GetAllLockerLogsPaginated.cs
  src/Application/Lockers/Queries/GetLockerLogById.cs
Labels: enhancement

#235 feat: implement get employees for the department the current user is in
  src/Api/Controllers/Payload/Requests/Users/GetAllEmployeesPaginatedQueryParameters.cs
  src/Api/Controllers/UsersController.cs
  src/Api/Services/CurrentUserService.cs
  src/Application/Users/Queries/GetAllEmployeesPaginated.cs
  src/Infrastructure/Identity/IdentityService.cs
Labels: enhancement

#241 feat: get room log by ID and get room logs paginated
  src/Api/Controllers/RoomsController.cs
  src/Application/Common/Models/Dtos/Logging/RoomLogDto.cs
  src/Application/Rooms/Queries/GetAllRoomLogsPaginated.cs
  src/Application/Rooms/Queries/GetLogOfRoomById.cs
Labels: enhancement

#257 feat: implement get request logs paginated + get request log by id
  src/Api/Controllers/BorrowsController.cs
  src/Application/Borrows/Queries/GetAllRequestLogsPaginated.cs
  src/Application/Borrows/Queries/GetRequestLogById.cs
  src/Application/Common/Models/Dtos/Logging/RequestLogDto.cs
Labels: enhancement

#238 feat: get self documents
  src/Api/Controllers/DocumentsController.cs
  src/Api/Controllers/Payload/Requests/Documents/GetSelfDocumentsPaginatedQueryParameters.cs
  src/Application/Documents/Queries/GetSelfDocumentsPaginated.cs
Labels: enhancement

#226 refactor: seperate cors rules for environments
  docker-compose.yml
  src/Api/Common/CORSPolicy.cs
  src/Api/ConfigureServices.cs
  src/Api/Extensions/WebApplicationExtensions.cs
  src/Api/Program.cs
Labels: enhancement, refactoring

#260 [Snyk] Security upgrade MailKit from 4.0.0 to 4.1.0
  src/Application/Application.csproj
Labels: bug, security

#220 feat: implement add user group.
  src/Application/UserGroups/Commands/CreateUserGroup.cs
  tests/Application.Tests.Integration/UserGroups/Commands/CreateUserGroupTests.cs
Labels: enhancement, test

#223 feat: implement update user group
  src/Application/UserGroups/Commands/UpdateUserGroup.cs
  tests/Application.Tests.Integration/UserGroups/Commands/UpdateUserGroupTests.cs
Labels: enhancement, test

#222 feat: implement delete user group
  src/Application/UserGroups/Commands/DeleteUserGroup.cs
  tests/Application.Tests.Integration/UserGroups/Commands/DeleteUserGroupTests.cs
Labels: enhancement, test

#225 feat: implement get user group
  src/Application/UserGroups/Queries/GetAllUserGroupsPaginated.cs
  src/Application/UserGroups/Queries/GetUserGroupById.cs
  tests/Application.Tests.Integration/UserGroups/Queries/GetAllUserGroupsPaginatedTests.cs
  tests/Application.Tests.Integration/UserGroups/Queries/GetUserGroupByIdTests.cs
Labels: enhancement, test

#262 add: seed staff data
  src/Infrastructure/Persistence/ApplicationDbContextSeed.cs
Labels: enhancement

#282 Fix: assign staff + get document by id
  src/Api/Controllers/DepartmentsController.cs
  src/Api/Controllers/StaffsController.cs
  src/Application/Documents/Queries/GetDocumentById.cs
  src/Application/Rooms/Queries/GetRoomByDepartmentId.cs
  src/Application/Rooms/Queries/GetRoomByStaffId.cs
  src/Application/Staffs/Commands/AssignStaff.cs
  src/Infrastructure/Persistence/ApplicationDbContextSeed.cs
Labels: bug

#280 update: get all rooms now has availability
  src/Api/Controllers/Payload/Requests/Rooms/GetAllRoomsPaginatedQueryParameters.cs
  src/Api/Controllers/RoomsController.cs
  src/Application/Rooms/Queries/GetAllRoomsPaginated.cs
Labels: enhancement

#308 delete: everything of user group
  src/Application/Common/Interfaces/IApplicationDbContext.cs
  src/Application/Common/Models/Dtos/Digital/UserGroupDto.cs
  src/Application/Common/Models/Dtos/UserDto.cs
  src/Application/UserGroups/Commands/CreateUserGroup.cs
  src/Application/UserGroups/Commands/DeleteUserGroup.cs
  src/Application/UserGroups/Commands/UpdateUserGroup.cs
  src/Application/UserGroups/Queries/GetAllUserGroupsPaginated.cs
  src/Application/UserGroups/Queries/GetUserGroupById.cs
  src/Domain/Entities/Digital/UserGroup.cs
  src/Domain/Entities/User.cs
  src/Infrastructure/Persistence/ApplicationDbContext.cs
  src/Infrastructure/Persistence/Configurations/UserGroupConfiguration.cs
  tests/Application.Tests.Integration/BaseClassFixture.cs
  tests/Application.Tests.Integration/UserGroups/Commands/CreateUserGroupTests.cs
  tests/Application.Tests.Integration/UserGroups/Commands/DeleteUserGroupTests.cs
  tests/Application.Tests.Integration/UserGroups/Commands/UpdateUserGroupTests.cs
  tests/Application.Tests.Integration/UserGroups/Queries/GetAllUserGroupsPaginatedTests.cs
  tests/Application.Tests.Integration/UserGroups/Queries/GetUserGroupByIdTests.cs
  tests/Application.Tests.Unit/Common/Mappings/MappingTests.cs
Labels: wontfix, refactoring
